# Railway Configuration for Default Rate API
# Using current Railway configuration format

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"

# AUTO-SCALING CONFIGURATION FOR RAILWAY
# These settings enable Railway to auto-scale your worker service
[deploy.autoscaling]
enabled = true
minReplicas = 2     # Minimum 2 instances (16 workers total)
maxReplicas = 8     # Maximum 8 instances (64 workers total)

# Scale up when CPU usage > 70% for 2 minutes
[deploy.autoscaling.triggers]
cpu = { target = 70, duration = "2m" }
memory = { target = 85, duration = "1m" }

# Scale down when CPU usage < 30% for 10 minutes  
[deploy.autoscaling.scaleDown]
cpu = { target = 30, duration = "10m" }
stabilizationWindow = "5m"  # Wait 5 minutes before scaling down

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
API_V1_STR = "/api/v1"
PROJECT_NAME = "Default Rate API"
