# Nixpacks configuration for Railway deployment with Neon PostgreSQL
[variables]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "pkg-config", "postgresql"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.prod.txt"
]

[phases.build]
cmds = [
    "python -c 'import sys; print(f\"Python version: {sys.version}\")'",
    "pip list | grep -E '(fastapi|uvicorn|sqlalchemy|psycopg2)'",
    "ls -la app/",
    "echo 'Build completed successfully'"
]

[start]
cmd = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
