# Railway Configuration for Default Rate API
# Using current Railway configuration format

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"

[environments.production.variables]
ENVIRONMENT = "production"
DEBUG = "false"
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
API_V1_STR = "/api/v1"
PROJECT_NAME = "Default Rate API"
