# Railway Service Configuration for Celery Worker
# Create a separate Railway service with this configuration

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./deployment/scripts/start-worker.sh"
restartPolicyType = "always"
healthcheckTimeout = 300

[environments.production]
variables = { 
  DEBUG = "false",
  PYTHONUNBUFFERED = "1",
  PYTHONPATH = "/app",
  CELERY_BROKER_URL = "$REDIS_URL",
  CELERY_RESULT_BACKEND = "$REDIS_URL",
  DATABASE_URL = "$DATABASE_URL"
}